### ISSUE TITLE
skipping invalid mega link

### ISSUE THREAD

**Issue by carlzoo** [megous/megatools#157]
Hello,

I am trying to download this link:
<blockquote>
megadl 'https://mega.nz/#!UE5lTR5R!Wxy2Wyz94F95dG8BoHpBux3-xzAxGsM0Gk2vXf15Po4'
</blockquote>

I get

<blockquote>
WARNING: Skipping invalid Mega download link: https://mega.nz/#!UE5lTR5R!Wxy2Wyz94F95dG8BoHpBux3-xzAxGsM0Gk2vXf15Po4
</blockquote>

it seems to do that for all the other files I tried.
I am running on debian 7.

I found a similiar issue here:
https://github.com/megous/megatools/issues/43

Is login required to download a public URL? I tried logging into my account and importing it into my cloud drive, then using that link I get the same result.

**Comment by megous** [comment]
Hi, just add .co to the link like this for now, and it should work:

  megadl 'https://mega.co.nz/#!UE5lTR5R!Wxy2Wyz94F95dG8BoHpBux3-xzAxGsM0Gk2vXf15Po4'

this will be fixed in the next release.

**Comment by w0ts0n** [comment]
Still having this issue? Worked when I added .co.

**Comment by megous** [comment]
Unless you're using some old version, you should not have it.

**Comment by EverMineServer** [comment]
Fix it please!

**Comment by megous** [comment]
This is already fixed.

**Comment by MarioVilas** [comment]
This is not fixed, using version 1.10.2 which is the latest stable, the one featured in the website and the one all Debian based distros have.

**Comment by LordShenron** [comment]
Yes Just now i am having same issue. Its not fixed.

**Comment by hosseinhayati128** [comment]
I am having the same issue now 
and adding `.co` is not fixing it.

**Comment by LordShenron** [comment]
I have found a workaround to this. 
While the mega website loads the file, the link will look something like this
https://mega. nz/#F!1ckViaAS!u4NsQ72afaReujK5BUWeKQ
This type of the link is working fine as of now.

**Comment by MarioVilas** [comment]
@LordShenron I don't see the same thing while loading and can't turn my not working link into a working one...

**Comment by MarcoLucidi01** [comment]
Workaround which worked for me on version 1.10.2 (debian stable):

I had a link in this form:

    $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'

I replaced `file/` with `#!` and `#` with `!`:

    $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'

the download started and completed fine

**Comment by LordShenron** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

I can confirm this works too. You can also quickly copy the link while it loads and the link will be in the same format.

**Comment by MarioVilas** [comment]
I never saw the link "change" while loading but @MarcoLucidi01's solution worked for me. Should be a simple fix to megadl too I suppose :)

**Comment by MarioVilas** [comment]
So it's up to Debian stable to update then. :(

**Comment by dominikaaaa** [comment]
The fix isn't released on Ubuntu 20.04LTS repos, but @MarcoLucidi01's solution works.

**Comment by ReyvanZA** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

Can confirm this worked for me.

**Comment by yoshiko2000** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

works for me thanks for posting the fix.

**Comment by yuanzheng625** [comment]
> I have found a workaround to this.
> While the mega website loads the file, the link will look something like this
> https://mega. nz/#F!1ckViaAS!u4NsQ72afaReujK5BUWeKQ
> This type of the link is working fine as of now.
> 
> [Edit-1]
> Here is a screenshot of the screen while loading.
> [Screenshot](https://i.imgur.com/cIu8zai.png)

worked for me

**Comment by dominikaaaa** [comment]
@megous mind reopening this issue as it obviously isn't fixed in any packaged releases?

**Comment by HeyParkerJ** [comment]
If anyone is attempting to script the string replacements, this is something I whipped up in bash. Disclaimer - today is my first day writing bash, so I'm sure this is not perfect, but it is simple and it works.

```
  #!/bin/bash

  link="https://mega.nz/file/7RBAjDya#IYqV9j_f0Kox8sSQh0HPjOSN10bY5xhkmF0TRiyhS2Y"
  
  # Start by replacing the '#' with '!'
  replaceHashtag=${link/\#/!}

  # Then replace '/file/' with '/#!'
  partToReplace="\/file\/"
  replaceWith="/#!"
  finalLink=${replaceHashtag/$partToReplace/$replaceWith};

  echo "Final Link: $finalLink"
  
  megadl $finalLink;
```

**Comment by sleepyrazor** [comment]
hey guys i have a problem, my link has /file/ and multiples folders/, how can i do it guys 
what i do is i go to the folder link, that looks like this : 'https://mega.nz/folder/Vg5wVShJ#ZUFij1fAeqyExqvXxas4X_g'
and there i can see more folders, so imagine that i want to download all of them.
i replace in the link # with ! , file/ with ! and folder/ with #F! ''https://mega.nz/#F!Vg5wVShJ!ZUFij1fAeqyExqvXxas4X_g''
but it doesnt work neither :(  any ideas?

**Comment by sleepyrazor** [comment]
> hey guys i have a problem, my link has /file/ and multiples folders/, how can i do it guys
> what i do is i go to the folder link, that looks like this : 'https://mega.nz/folder/Vg5wVShJ#ZUFij1fAeqyExqvXxas4X_g'
> and there i can see more folders, so imagine that i want to download all of them.
> i replace in the link # with ! , file/ with ! and folder/ with #F! ''https://mega.nz/#F!Vg5wVShJ!ZUFij1fAeqyExqvXxas4X_g''
> but it doesnt work neither :( any ideas?

Actually i have now found the way to download, ty guys <3

**Comment by P4R0D-Y** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

Works fine. And in Version 1.10.3 its still not fixed the problem.

**Comment by MarioVilas** [comment]
I have a suggestion: perhaps the regular expressions to parse the links should be stored in a config file rather than hardcoded into the sources. That way it would be simpler to update without having to wait for Debian devs to come out of hibernation and notice the world has moved on without them :D

**Comment by wisewtf** [comment]
> If anyone is attempting to script the string replacements, this is something I whipped up in bash. Disclaimer - today is my first day writing bash, so I'm sure this is not perfect, but it is simple and it works.
> 
> ```
>   #!/bin/bash
> 
>   link="https://mega.nz/file/7RBAjDya#IYqV9j_f0Kox8sSQh0HPjOSN10bY5xhkmF0TRiyhS2Y"
>   
>   # Start by replacing the '#' with '!'
>   replaceHashtag=${link/\#/!}
> 
>   # Then replace '/file/' with '/#!'
>   partToReplace="\/file\/"
>   replaceWith="/#!"
>   finalLink=${replaceHashtag/$partToReplace/$replaceWith};
> 
>   echo "Final Link: $finalLink"
> ```

To expand on this, I made a somewhat similar script but to massively fix a list of links and input them directly into megadl:

`while read -r row; do
   row=${row/\#/!}
   partToReplace="\/file\/"
   replaceWith="/#!"
   row=${row/$partToReplace/$replaceWith}
   megadl "${row}"
done < links.txt`

Just have a links.txt file where you launch this script containing all links you need

**Comment by muralivijay** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

works well thanks man

**Comment by azzahrah** [comment]
great working

**Comment by HeyParkerJ** [comment]
> If anyone is attempting to script the string replacements, this is something I whipped up in bash. Disclaimer - today is my first day writing bash, so I'm sure this is not perfect, but it is simple and it works.
> 
> ```
>   #!/bin/bash
> 
>   link="https://mega.nz/file/7RBAjDya#IYqV9j_f0Kox8sSQh0HPjOSN10bY5xhkmF0TRiyhS2Y"
>   
>   # Start by replacing the '#' with '!'
>   replaceHashtag=${link/\#/!}
> 
>   # Then replace '/file/' with '/#!'
>   partToReplace="\/file\/"
>   replaceWith="/#!"
>   finalLink=${replaceHashtag/$partToReplace/$replaceWith};
> 
>   echo "Final Link: $finalLink"
> ```

To follow up on this, I ended up publishing the script I wrote, which might be a good launching point for someone interested in the same. The features and usage instructions are documented.

https://github.com/HeyParkerJ/batch_megadl/blob/master/batch_megadl.sh

**Comment by shanaka95** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

Thanks

**Comment by BlackMetalz** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

Yes. It works. LOL :laughing:

**Comment by Char11e** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

It doesn't work in ubuntu 20.04
my megatools is 1.10.3 version
I always  get a html file back

**Comment by chenqili2020** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

This worked for me

**Comment by alfredonodo** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

It seems that the workaround stopped working since version 1.11.0. Any idea?
Thank you

**Comment by MarcoLucidi01** [comment]
> It seems that the workaround stopped working since version 1.11.0. Any idea?

@alfredonodo that's strange, newer versions usually don't need the workaround anymore. I have 1.10.3 (debian stable) and works fine. just tried 1.11.0 and works fine too. can you share some non-working link?

**Comment by alfredonodo** [comment]
> > It seems that the workaround stopped working since version 1.11.0. Any idea?
> 
> @alfredonodo that's strange, newer versions usually don't need the workaround anymore. I have 1.10.3 (debian stable) and works fine. just tried 1.11.0 and works fine too. can you share some non-working link?

I found that the version 1.11.0 is compatible with the new format https://mega.nz/folder/<some_id>#<some_other_id> instead of the previous one https://mega.co.nz/#F!<some_id>!<some_other_id>. The workaround worked up to 1.10.2 if I'm not wrong.

**Comment by MarcoLucidi01** [comment]
> I found that the version 1.11.0 is compatible with the new format

yes new versions usually don't need the workaround. if you have no troubles downloading files, then I'm not understanding what your problem/complain is.

**Comment by alfredonodo** [comment]
> > I found that the version 1.11.0 is compatible with the new format
> 
> yes new versions usually don't need the workaround. if you have no troubles downloading files, then I'm not understanding what your problem/complain is.

I was using the old format, but with the latest version (automatically updated). After a while, I discovered that starting from 1.10.3 the new format is mandatory. So thank you.

**Comment by dbedrenko** [comment]
> @alfredonodo  can you share some non-working link?

https://mega.nz/#F!lVFxEApB!y-tzXWNuQya2iuBDHsO2gw
https://mega.nz/folder/lVFxEApB#y-tzXWNuQya2iuBDHsO2gw/file/1QsRESIZ


Both get skipped on latest 1.11.0 even with workarounds in this thread.

**Comment by MarcoLucidi01** [comment]
> https://mega.nz/#F!lVFxEApB!y-tzXWNuQya2iuBDHsO2gw
> https://mega.nz/folder/lVFxEApB#y-tzXWNuQya2iuBDHsO2gw/file/1QsRESIZ
>
> Both get skipped on latest 1.11.0 even with workarounds in this thread.

second link (new format) worked fine for me using latest 1.11.0 (taken [here](https://megatools.megous.com/builds/experimental/)):

```
$ ./megatools dl 'https://mega.nz/folder/lVFxEApB#y-tzXWNuQya2iuBDHsO2gw/file/1QsRESIZ'
F /home/marco/downloads/megatools-1.11.0-git-20211030-linux-x86_64/ADK.World.NEO4ALL.RC4-RDC.7z
$ sha256sum ADK.World.NEO4ALL.RC4-RDC.7z
b5e26ead45f59528c5a4e7a3251dcccdc66e29b90954c5c1ab4aa5183dc9ff98  ADK.World.NEO4ALL.RC4-RDC.7z
```

first link (old format) gave me an error:

```
$ ./megatools dl 'https://mega.nz/#F!lVFxEApB!y-tzXWNuQya2iuBDHsO2gw'
ERROR: Can't open folder 'https://mega.nz/#F!lVFxEApB!y-tzXWNuQya2iuBDHsO2gw': Node not found:
```

which I "resolved" applying the workaround in "reverse" i.e. replace `#F!` with `folder/` and `!` with `#`:

```
$ ./megatools dl 'https://mega.nz/folder/lVFxEApB#y-tzXWNuQya2iuBDHsO2gw'
F /home/marco/downloads/megatools-1.11.0-git-20211030-linux-x86_64/ADK.World.NEO4ALL.RC4-RDC.7z
$ sha256sum ADK.World.NEO4ALL.RC4-RDC.7z
b5e26ead45f59528c5a4e7a3251dcccdc66e29b90954c5c1ab4aa5183dc9ff98  ADK.World.NEO4ALL.RC4-RDC.7z
```

**Comment by alfredonodo** [comment]
> > https://mega.nz/#F!lVFxEApB!y-tzXWNuQya2iuBDHsO2gw
> > https://mega.nz/folder/lVFxEApB#y-tzXWNuQya2iuBDHsO2gw/file/1QsRESIZ
> > Both get skipped on latest 1.11.0 even with workarounds in this thread.
> 
> second link (new format) worked fine for me using latest 1.11.0 (taken [here](https://megatools.megous.com/builds/experimental/)):
> 
> ```
> $ ./megatools dl 'https://mega.nz/folder/lVFxEApB#y-tzXWNuQya2iuBDHsO2gw/file/1QsRESIZ'
> F /home/marco/downloads/megatools-1.11.0-git-20211030-linux-x86_64/ADK.World.NEO4ALL.RC4-RDC.7z
> $ sha256sum ADK.World.NEO4ALL.RC4-RDC.7z
> b5e26ead45f59528c5a4e7a3251dcccdc66e29b90954c5c1ab4aa5183dc9ff98  ADK.World.NEO4ALL.RC4-RDC.7z
> ```
> 
> first link (old format) gave me an error:
> 
> ```
> $ ./megatools dl 'https://mega.nz/#F!lVFxEApB!y-tzXWNuQya2iuBDHsO2gw'
> ERROR: Can't open folder 'https://mega.nz/#F!lVFxEApB!y-tzXWNuQya2iuBDHsO2gw': Node not found:
> ```
> 
> which I "resolved" applying the workaround in "reverse" i.e. replace `#F!` with `folder/` and `!` with `#`:
> 
> ```
> $ ./megatools dl 'https://mega.nz/folder/lVFxEApB#y-tzXWNuQya2iuBDHsO2gw'
> F /home/marco/downloads/megatools-1.11.0-git-20211030-linux-x86_64/ADK.World.NEO4ALL.RC4-RDC.7z
> $ sha256sum ADK.World.NEO4ALL.RC4-RDC.7z
> b5e26ead45f59528c5a4e7a3251dcccdc66e29b90954c5c1ab4aa5183dc9ff98  ADK.World.NEO4ALL.RC4-RDC.7z
> ```

I can confirm this.

**Comment by dbedrenko** [comment]
Ah I realised what was going wrong from comparing my input to yours. `zsh` was escaping the `#` with a backslash automatically when I paste the link:

```
$ megatools dl 'https://mega.nz/folder/lVFxEApB\#y-tzXWNuQya2iuBDHsO2gw/file/1QsRESIZ'
WARNING: Skipping invalid Mega download link: https://mega.nz/folder/lVFxEApB\#y-tzXWNuQya2iuBDHsO2gw/file/1QsRESIZ
```

Thank you both for confirming.

**Comment by robjbrain** [comment]
If you're stuck on an old version this very simple bash script will let you use either url format

```
#!/bin/bash
#https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w
#https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w
#Swap "file" for #! and swap # for !
if [[ $1 ]]
then
  URL="$1"
  if [[ $URL =~ file/(.*)#(.*) ]]; then
    megadl "https://mega.nz/#!${BASH_REMATCH[1]}!${BASH_REMATCH[2]}"
  else
    megadl $1
  fi
else
  echo 'Mega Link is required'
fi
```

**Comment by maravento** [comment]
> Workaround which worked for me on version 1.10.2 (debian stable):
> 
> I had a link in this form:
> 
> ```
> $ megadl 'https://mega.nz/file/7YVWhCzZ#bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> I replaced `file/` with `#!` and `#` with `!`:
> 
> ```
> $ megadl 'https://mega.nz/#!7YVWhCzZ!bauBlAkKKvv8hIm-8-qFmGOYS289ToQWN7rGFPzXB_w'
> ```
> 
> the download started and completed fine
> 
> edit: it works for folders links too, just replace `folder/` with `#F!` and `#` with `!`

confirm works for ubuntu 20.04.3. thanks

**Comment by megapro17** [comment]
Omfg this shit is still not working even with experimental 1.11.0 version with this link https://mega.nz/file/kaYgWTQC#4WWoHqO7rMZ66I2RIevKRlWRNdD5-lUYhNbWWXTsypQ=

**Comment by maravento** [comment]
> Omfg this shit is still not working even with experimental 1.11.0 version with this link https://mega.nz/file/kaYgWTQC#4WWoHqO7rMZ66I2RIevKRlWRNdD5-lUYhNbWWXTsypQ=

your link is wrong. try this:

`megadl 'https://mega.nz/#!kaYgWTQC!4WWoHqO7rMZ66I2RIevKRlWRNdD5-lUYhNbWWXTsypQ'`

megadl --version
megatools 1.10.2 - command line tools for Mega.nz

**Comment by HellishINC** [comment]
Thanks for the workaround. Sad that this 7 year old issue still exists.

**Comment by Belox17** [comment]
Is there now a solution?

**Comment by megapro17** [comment]
It does with experimental version and specifically formatted link

**Comment by Belox17** [comment]
And it is possible to skip a banned link? Like download all the content of the link before it was banned? Thx in advance
