### ISSUE TITLE
Problem download large files with megatools 1.10

### ISSUE THREAD

**Issue by Poisonfish** [megous/megatools#380]
problem was upload files to mega, but was not problem download large files.
Now, with new 1.10 i can upload large files but cannot download..
after reaching 500-600Mb connection drops..:

error:

ERROR: Download failed for '/myshare/qemu/ise-2.3.0.298.SPA.tar.gz': Data download failed: CURL error: Failure when receiving data from the peer

any advice?

**Comment by megous** [comment]
Sorry for that. Should be fixed in 1.10.1.

**Comment by megous** [comment]
See: https://megatools.megous.com/builds/

**Comment by liar666** [comment]
Got version "megatools-1.10.1-win64.zip" still getting error:
"Data download failed: CURL error: Failure when receiving data from the peer"

**Comment by megous** [comment]
Run wiht --debug http

**Comment by megous** [comment]
Send output to megous@megous.com and clear the active sessions in mega.nz ui to be safe.

**Comment by mobiuscog** [comment]
I'm also seeing this. It also occurred in 0.99 which had been working recently, so I updated to the latest github source, which has the same problem described above. Perhaps it is a change elsewhere ?

**Comment by megous** [comment]
Mega just started immediately closing connections after sending a proper response header, but before sending data for downloads of big files.

**Comment by megous** [comment]
I've got other reports of this too.

**Comment by megous** [comment]
Either a bug on their side, or they're changing the download APIs for whatever reason.

**Comment by t0rzz** [comment]
FYI, it's still happening as of today with v1.10.1 any file I'm trying to download with "megadl 'link'".

```
root@serv:/HDD/Movies# megadl 'https://mega.nz/#!vepX0RTQ!hUW95BPR26ywaqFXZ2s8x1yinkIj1miMYXTgdueoMxo' --debug
-> [{
        "a": "g",
        "g": 1,
        "ssl": 0,
        "p": "vepX0RTQ"
}]
<- [{
        "s": 2720174968,
        "at": "0mVtw1H6HcfXX5ke6fVO5DTrPpJpmUwe02dy1DM3LLFVLGjmdCJsUqpuRBIbnIMIOuTKAXETBtD3_SEezFBHiT0CydAnMDpi6XxgNDFe5k5RAoBX4xgE-XvomM8kNtMcIR7tpaE9fO2aDM4M1syk6Q",
        "msd": 1,
        "fa": "827:1*wUWnkTYLb_w/823:0*ZlnIUgH6agU/618:8*EtsgS0DarfA",
        "g": "http://gfs204n119.userstorage.mega.co.nz/dl/6xc70gaQg-RGEQJvLRFadUS_Rsp7QfgB3ZBuVm2BnhOg5CCoNc4RjppfaDdQKfxqW5sO8dr5pv7TeeqbSuDVgeJgo9t_nV2wCi2wRj1ODyQNWp3ibSKX5wz04jH6nA"
}]

ERROR: Download failed for 'https://mega.nz/#!vepX0RTQ!hUW95BPR26ywaqFXZ2s8x1yinkIj1miMYXTgdueoMxo': Data download failed: CURL error: Failure when receiving data from the peer

```
Thanks for your support.

**Comment by bencaradocdavies** [comment]
I also see this failure with 1.10.0 from .deb (using libcurl4) and 1.10.1 built from source (using libcurl3) on debian/sid amd64. The failure occurs every time with a 3.0 GiB file. Debug http output (slightly sanitised):
```
$ megaget --debug http /Root/EXPUNGED/EXPUNGED
*   Trying 31.216.147.136...
* TCP_NODELAY set
* Connected to g.api.mega.co.nz (31.216.147.136) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NZ; postalCode=1010; ST=Auckland; L=Auckland; street=15, Pwc Tower, 188 Quay Street,; O=Mega Limited; OU=PremiumSSL Wildcard; CN=*.api.mega.co.nz
*  start date: Dec 11 00:00:00 2017 GMT
*  expire date: Dec 10 23:59:59 2020 GMT
*  subjectAltName: host "g.api.mega.co.nz" matched cert's "*.api.mega.co.nz"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
> POST /cs?id=EXPUNGED&sid=EXPUNGED HTTP/1.1
Host: g.api.mega.co.nz
Accept-Encoding: deflate, gzip
Accept: */*
DNT: 1
Pragma: no-cache
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
Accept-Language: en-US;q=0.8,en;q=0.3
Content-Type: application/json
Origin: https://mega.nz
Referer: https://mega.nz/
Cache-Control: no-cache
Content-Length: 43

* upload completely sent off: 43 out of 43 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Content-Type, MEGA-Chrome-Antileak
< Access-Control-Expose-Headers: Original-Content-Length
< Access-Control-Max-Age: 86400
< Original-Content-Length: 275
< Content-Length: 275
< Connection: keep-alive
< 
* Connection #0 to host g.api.mega.co.nz left intact
*   Trying 122.56.56.205...EXPUNGED: 0.00% - 0 bytes of 3.0 GiB
* TCP_NODELAY set
* Connected to gfs530n012.userstorage.mega.co.nz (122.56.56.205) port 80 (#0)
> POST /dl/EXPUNGED HTTP/1.1
Host: gfs530n012.userstorage.mega.co.nz
Accept-Encoding: deflate, gzip
Accept: */*
DNT: 1
Pragma: no-cache
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
Accept-Language: en-US;q=0.8,en;q=0.3
Origin: https://mega.nz
Referer: https://mega.nz/
Cache-Control: no-cache
Content-Length: 0
Content-Type: application/x-www-form-urlencoded

< HTTP/1.1 200 OK
< Content-Length: 3238577510
< Content-Type: application/octet-stream
< Content-Disposition: attachment
< Cache-Control: private
< Content-Transfer-Encoding: binary
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: MEGA-Chrome-Antileak
< Access-Control-Max-Age: 86400
< 
* Recv failure: Connection reset by peer 0 bytes of 3.0 GiB (0 bytes/s)
* stopped the pause stream!
* Closing connection 0

ERROR: Download failed for '/Root/EXPUNGED/EXPUNGED': Data download failed: CURL error: Failure when receiving data from the peer
```

**Comment by megous** [comment]
Yes, me too. Yes, mega changed something and started dropping large downloads. It now probably requires a chunked download to download large files successfully. That's a bit of a PITA to implement, although less so than before all the upload code refactoring in the last few weeks.

I've already spent too much time on megatools last few weeks so don't expect a quick solution now. I'm way down in red numbers when it comes to benefit I'm gaining from all this. Without other people contributing, it's somewhat pointless since I'm not using megatools/mega.nz myself much at all.

It's fun optimizing stuff. I liked that. But chasing stupid pointless mega.nz changes that simply break things for no apparent reason week after week, with almost zero benefit to myself... I have better things to do. Ask mega to allow big downloads again.

**Comment by bencaradocdavies** [comment]
At least large uploads work again after your fix for #360. Mega: the write-only cloud storage provider.

**Comment by t0rzz** [comment]
@megous 
>  It now probably requires a chunked download to download large files successfully.

You're probably right.
From my tests, there are two files in the root of mega.nz: decrypter.js and aesasm.js.
The browser makes POST requests on different locations with an always changing Content-Length response header. No idea about what can be done. If those 2 JS are required, CURL won't work.

Some network testing:
![immagine](https://user-images.githubusercontent.com/21285290/43373335-4dda552e-93a9-11e8-9b19-96321b7456ee.png)

**Comment by megous** [comment]
@t0rzz mega.nz did this "chunked download" since the beginning. cURL will work fine. It's just necessary to rework the code so that it does multiple POST requests in sequence as opposed to a single big one.

**Comment by Nico205** [comment]
Hey there...I really relay on the program and am a huge fan.
I'll donate some bucks if you going to give me your PayPal mail for a fast fix :)

**Comment by megous** [comment]
@Nico205 Send me an e-mail to megous@megous.com, I'll send you my paypal account e-mail in the reply. Thanks!

**Comment by t0rzz** [comment]
@megous Why don’t you add your PayPal email address on the header of the project page? I’d like to donate too.

**Comment by megous** [comment]
@t0rzz I have an e-mail system where I need to have (randomly generated) e-mail addresses I associate with online accounts private. Otherwise it loses some of its nice properties. Though I have now just realized that I can add my public email address to Paypal as a secondary address and it will hopefully be able to receive payments too. So now it should be possible to donate to megous@megous.com, my public address. You can test it if you like. Thank you.

**Comment by megous** [comment]
I'll probably try adding PayPal button somewhere. I had paypal address mentioned on the website and on github before, and it never received anything. It should be easier for people than copying addresses around, I guess.

**Comment by liar666** [comment]
Works like a charm here!

Thanks a lot megous!!!!!

**Comment by megous** [comment]
Good to know. :)

**Comment by t0rzz** [comment]
Fix is working. Thanks :) Will send a donation immediately to megous@megous.com. @megous

**Comment by bencaradocdavies** [comment]
I can confirm that 1.10.2 fixes #380 for me, tested with megaget for the same 3.0 GiB file that failed with 1.10.0 and 1.10.1.

**Comment by megous** [comment]
I'm glad it works, and thanks for all the donations. I tried to send individual thanks via e-mail, but in case some messages got delivered to spam, thank you! :)

**Comment by eczema** [comment]
20$ sent to say thank you  !

**Comment by t0rzz** [comment]
I’m glad people like me realized that an act of kindness is always accepted when you freely use code written by others.

**Comment by the3ye** [comment]
How can I get 1.10.2 on macOS? brew still installs or upgrades to 1.10.1...

**Comment by t0rzz** [comment]
@the3ye can't you compile it by sources? Install command line tools for xcode and try to compile it

**Comment by vejkse** [comment]
It looks like that the speed limit specified with --limit-speed is only respected for the first chunk.

**Comment by megous** [comment]
@vejkse I looked quickly through the code, and limit seems to be set in a way that it will be reused. I'll test later.

**Comment by megous** [comment]
@vejkse It was a bug in curl. I worked around it.
